version: 2

sources:
  - name: raw
    database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
    schema: '{{ env_var("SNOWFLAKE_SCHEMA") }}'
    config:
      meta:
        dagster:
          auto_materialize_policy:
            type: eager
    tables:
      - name: heart_rate_stream
        description: Heart rate records loaded from S3 bucket
        tests:
            - airbyte_meta_no_errors
            - unique:
                column_name: "(user_id || '-' || timestamp)"
            - dbt_expectations.expect_table_columns_to_match_set:
                column_list: ["_airbyte_raw_id", "_airbyte_extracted_at", "_ab_source_file_url", "_ab_source_file_last_modified", "_airbyte_meta", "meta", "user_id", "timestamp", "heart_rate"]    
        columns:
          - name: _airbyte_raw_id
            description: Unique identifier for each raw heart rate data record provided by Airbyte
            tests:
              - unique
              - not_null 
          - name: _airbyte_extracted_at
            description: Timestamp indicating when the heart rate data was extracted by Airbyte
            tests:
              - not_null 
          - name: _airbyte_meta
            description: Metadata provided by Airbyte (should be empty)
          - name: _ab_source_file_url
            description: URL path of file from S3 bucket where heart rate record was extracted from (should follow a standard pattern).
            tests:
              - dbt_expectations.expect_column_values_to_match_like_pattern:
                  like_pattern: "topics/hr-data-topic/year=%/month=%/day=%/hour=%/hr-data-topic+_+%.json"
          - name: _ab_source_file_last_modified
            description: Timestamp indicating the last modification of the S3 bucket source file 
          - name: meta
            description: Additional metadata related to the heart rate measurement
            tests:
              - not_null 
          - name: user_id
            description: Unique identifier for each user
            tests:
              - not_null 
          - name: timestamp
            description: Event time of the heart rate measurement
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  # Event time should be between 1 April 2024 and 31 December 2025
                  min_value: 1711929600
                  max_value: 1767229200
          - name: heart_rate
            description: Heart rate value in beats per minute (BPM)
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 5  
                  max_value: 300
      
      - name: users
        description: Users data extracted from OLTP system
        tests:
            - airbyte_meta_no_errors
            - unique:
                column_name: "(user_id || '-' || _ab_cdc_updated_at)"
            - dbt_expectations.expect_table_columns_to_match_set:
                column_list: ["_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_ab_cdc_lsn", "_ab_cdc_deleted_at", "_ab_cdc_updated_at", "sex", "race", "height", "weight", "address", "user_id", "last_name", "blood_type", "first_name", "last_update", "date_of_birth", "origin_country_code", "origin_country_name", "address_country_code", "address_country_name"] 
        columns:
          - name: _airbyte_raw_id
            description: Unique identifier for each raw user data record provided by Airbyte
            tests:
              - unique
              - not_null 
          - name: _airbyte_extracted_at
            description: Timestamp indicating when the user data was extracted by Airbyte
            tests:
              - not_null 
          - name: _airbyte_meta
            description: Metadata provided by Airbyte (should be empty)
          - name: _ab_cdc_lsn
            description: Log sequence number provided by Airbyte CDC 
          - name: _ab_cdc_deleted_at
            description: Timestamp indicating when the user record was deleted (if applicable)
          - name: _ab_cdc_updated_at
            description: Timestamp indicating when the user record was last updated by Airbyte CDC
          - name: sex
            description: User sex 
          - name: race
            description: User race 
            tests:
              - accepted_values:
                  values: ['W', "H", "B", "A", "O"]
          - name: height
            description: User height 
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 100  
                  max_value: 300
          - name: weight
            description: User weight 
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 30  
                  max_value: 500
          - name: address
            description: User address
          - name: user_id
            description: Unique identifier for each user
            tests:
              - not_null 
              - dbt_expectations.expect_column_values_to_be_between:
                  # Standard identifier values range chosen when designing OLTP database
                  min_value: 10001  
                  max_value: 19999
          - name: first_name
            description: User first name 
          - name: last_name
            description: User last name 
          - name: blood_type
            description: User blood type 
            tests:
              - accepted_values:
                  values: ['A+', "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
          - name: date_of_birth
            description: User date of birth 
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 19000101  
                  max_value: 20991231
                  row_condition: "date_of_birth>0" # to eliminate airbyte deleted_at rows with 0 as the default value for column
                  strictly: true
          - name: origin_country_code
            description: Two letter code (Alpha-2) of the country of origin for the user
            tests:
              - relationships:
                  to: ref('country_codes')
                  field: alpha2
          - name: origin_country_name
            description: Name of the country of origin for the user
            tests:
              - relationships:
                  to: ref('country_codes')
                  field: name
          - name: address_country_code
            description: Two letter code (Alpha-2) of the country where the user lives
            tests:
              - relationships:
                  to: ref('country_codes')
                  field: alpha2
          - name: address_country_name
            description: Name of the country where the user lives
            tests:
              - relationships:
                  to: ref('country_codes')
                  field: name
          - name: last_update
            description: Timestamp indicating the last update for the user data
        
      - name: activities
        description: Activity names extracted from OLTP system
        tests:
            - airbyte_meta_no_errors
            - unique:
                column_name: "(activity_id || '-' || _ab_cdc_updated_at)"
            - dbt_expectations.expect_table_columns_to_match_set:
                column_list: ["_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_ab_cdc_lsn", "_ab_cdc_deleted_at", "_ab_cdc_updated_at", "activity_id",  "activity_name", "last_update"]
        columns:
          - name: _airbyte_raw_id
            description: Unique identifier for each raw activity data record provided by Airbyte
            tests:
              - unique
              - not_null 
          - name: _airbyte_extracted_at
            description: Timestamp indicating when the activity data was extracted by Airbyte
            tests:
              - not_null 
          - name: _airbyte_meta
            description: Metadata provided by Airbyte (should be empty)
          - name: _ab_cdc_lsn
            description: Log sequence number provided by Airbyte CDC 
          - name: _ab_cdc_deleted_at
            description: Timestamp indicating when the activity record was deleted (if applicable)
          - name: _ab_cdc_updated_at
            description: Timestamp indicating when the activity record was last updated by Airbyte CDC
          - name: activity_id
            description: Unique identifier for each activity
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  # Standard identifier values range chosen when designing OLTP database
                  min_value: 20000   
                  max_value: 20999
          - name: activity_name
            description: Name of the activity
          - name: last_update
            description: Timestamp indicating the last update of the activity data
          