version: 2

models:
  - name: stg_activities
    columns:
      - name: activity_id
        description: Composite key to uniquely identify the activity in the operational system.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 20000  
              max_value: 20999

  - name: stg_heart_rates
    columns:
      - name: heart_rate
        description: Heart rate values from stream.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 5  
              max_value: 300

  - name: stg_users
    columns:
      - name: blood_type
        description: Blood type of each user.
        tests:
          - accepted_values:
              values: ['A+', "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]